[[redirects]]
    from = "https://k16e.co/blog/ideas/possible-component-names"
    to = "https://k16e.co/blog/ideas/dictionary"
    status = 301
    force = true

[[redirects]]
    from = "https://k16e.com/*"
    to = "https://k16e.co/:splat"
    status = 301
    force = true

[build]
    command = "npm cache clean --force && npm i --force && npm run build"
    publish = "dist"

[build.environment]
    NODE_VERSION = "20"
    NPM_VERSION = "10"